Add the newsletter template page, and associated styles.
thundernest/thunderblog pull request #38
Opened 2022-12-20 22:37 UTC by MelissaAutumn

Associated ticket: #34 

The Newsletter WordPress page will use this template to embed the mailchimp signup form.

Page in action:
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/97147377/208779367-5a3e784c-3e6c-4bc0-a74e-e007591433f7.png">

Also pinging @KillYourFM for visual feedback. It's not live yet, since this code needs to go up before the sign-up form can be displayed.

2022-12-21 15:46 UTC, micahilbery requested changes
With the button and input I would say we should either give it some gap between them or change the border radius of the subscribe button to be `0 var(--border-radius) var(--border-radius) 0` so that it looks like they are attached. I'm not sure the preferred option.

2022-12-21 18:02 UTC, MelissaAutumn commented
Good spot, after some thinking, I've adjusted so there's a gap between. Looks more like the search bar now, which also fits in with the thunderbird style guide. 
 
<img width="796" alt="image" src="https://user-images.githubusercontent.com/97147377/208973262-5f11377b-bc88-451e-8f70-2c1418d6a5d1.png">

2022-12-21 19:45 UTC, Alecaddd commented
Little fly by comment that I'm sure everyone will love, but I think it would be nice to have a consistent style with the way the subscription input field is styled in the main website.

![Screenshot from 2022-12-21 11-39-55](https://user-images.githubusercontent.com/2527103/208989682-49227542-7524-4826-a81f-2e8833c22f03.png)

On some more nitpicky notes:
- The input field should have a placeholder
- The input field should have the same border radius of  the button
- I would give the form a `max-width` smaller than the post, so to make it centered aligned and not as wide as the whole post since it doesn't need it, and very long input fields "feel" strange.

2022-12-21 20:25 UTC, MelissaAutumn commented
Sounds good, I was aiming for that originally but wanted to keep it within blog style. I'll cook something more similar up. Thanks for the fly-by feedback!

2022-12-21 21:49 UTC, MelissaAutumn commented
Slightly more in-line with Thunderbird.net, but still very thunderblog. 

<img width="851" alt="image" src="https://user-images.githubusercontent.com/97147377/209008289-70caac3b-989e-4064-ae0b-fefbede05612.png">

2022-12-21 22:17 UTC, micahilbery approved these changes
Style wise, looks good to me! Thank you!

2022-12-22 17:08 UTC, MelissaAutumn commented
I was going to put this on hold until newsletter situation was clarified, but I'll merge this and put the ticket on hold.

2022-12-22 17:09 UTC, merged